######################################################################
# Automatically generated by qmake (3.0) Mon May 15 07:33:01 2017
######################################################################

TEMPLATE = app
TARGET = access
INCLUDEPATH += .

# Input
SOURCES += access.cpp

QT -= gui
