######################################################################
# Automatically generated by qmake (3.0) Mon May 15 07:33:01 2017
######################################################################

TEMPLATE = app
TARGET = html_escape
INCLUDEPATH += .

# Input
SOURCES += html_escape.cpp

QT -= gui
