######################################################################
# Automatically generated by qmake (3.0) Mon May 15 07:33:01 2017
######################################################################

TEMPLATE = app
TARGET = right_align
INCLUDEPATH += .

# Input
SOURCES += right_align.cpp

QT -= gui
